server:
  port: 8080

spring:
  application:
    name: blogapp

  #  db configurations
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app
    username: root
    password: 123*Priyanka
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


security:
  jwt:
    secret: 24tqfweqhfofjwfjhwfwoijdfqwbdpojfwfbhwfnwjhfdbijoqwhoqfbqifhqagrasgasgafasgadfweatesbsadgsdhbsagshag
    access-token-expire-time: 600000
    refresh-token-expire-time: 3600000
    issuer: substring-blog-app

#Dialect
#driver classname

logging:
  level:
    com.blog_app: DEBUG
    org.springframework.security: DEBUG
#Dialect
#driver classname

